### ISSUE TITLE
Semantic types

### ISSUE THREAD

**Issue by dennwc** [bblfsh/sdk#260]
Implement all the code necessary to support Semantic UAST types.

**TODO:**
- [x] New pipeline step
- [x] High-level helpers for defining semantic mappings
- [x] Low-level helpers to support operations required by drivers
- [x] Strict type checks for semantic types
- [x] Basic tests for reversibility
