### ISSUE TITLE
Implement semantic types in drivers

### ISSUE THREAD

**Issue by dennwc** [bblfsh/sdk#261]
Implement UAST normalization for semantic types defined in https://github.com/bblfsh/sdk/issues/260.

**TODO:**
- [x] Go (https://github.com/bblfsh/go-driver/pull/20)
- [x] Java (https://github.com/bblfsh/java-driver/pull/79)
- [x] JavaScript (https://github.com/bblfsh/javascript-driver/pull/20)
- [x] Python (https://github.com/bblfsh/python-driver/pull/157)
- [x] PHP (https://github.com/bblfsh/php-driver/pull/17)
- [x] Ruby (https://github.com/bblfsh/ruby-driver/pull/23)

**Comment by dennwc** [comment]
Done! :tada:
